# Generated by Django 4.1.6 on 2023-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="num_reviews",
            field=models.IntegerField(null=True, verbose_name="Number of Reviews"),
        ),
    ]
