# Generated by Django 4.1.6 on 2023-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_userprofile_num_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Profile Photo"
            ),
        ),
    ]
