# Generated by Django 4.1.5 on 2023-01-25 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_user_id_listing_owner_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
